// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package connector

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"baseURL": {
			Default:     "https://unifieddatalibrary.com",
			Description: "The Base URL to use to access the UDL. The default is https://unifieddatalibrary.com.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"dataMode": {
			Default:     "TEST",
			Description: "The Data Mode to use when submitting requests to the UDL. Acceptable values are REAL, TEST, SIMULATED and EXERCISE.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"endpoint": {
			Default:     "",
			Description: "The target UDL endpoint.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"httpBasicAuthPassword": {
			Default:     "",
			Description: "The HTTP Basic Auth Password to use when accessing the UDL.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"httpBasicAuthUsername": {
			Default:     "",
			Description: "The HTTP Basic Auth Username to use when accessing the UDL.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
