// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"baseURL": {
			Default:     "https://unifieddatalibrary.com",
			Description: "The Base URL to use to access the UDL. The default is https://unifieddatalibrary.com.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"dataMode": {
			Default:     "TEST",
			Description: "The Data Mode to use when submitting requests to the UDL. Acceptable values are REAL, TEST, SIMULATED and EXERCISE.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"REAL", "TEST", "SIMULATED", "EXERCISE"}},
			},
		},
		"dataType": {
			Default:     "AIS",
			Description: "The Data Type that is being submitted to the UDL. Acceptable values are AIS and ELSET.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"AIS", "ELSET"}},
			},
		},
		"httpBasicAuthPassword": {
			Default:     "",
			Description: "The HTTP Basic Auth Password to use when accessing the UDL.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"httpBasicAuthUsername": {
			Default:     "",
			Description: "The HTTP Basic Auth Username to use when accessing the UDL.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
